### ISSUE TITLE
about mobile browser

### ISSUE THREAD

**Issue by nvcken** [danilw/Castle-game#1]
This is cool, would you please tell how can check performance on mobile browser?
And how can check that api to do render/glsl almost supported on mobile browser (ios & android)

Thanks so much

**Comment by danilw** [comment]
this project use WebGL2 and Web Assembly
it absolutly "test" project with no real use, it 100% work on actual PC webbrowsers
this project do not have mobile support(even if it work, it was developed onyl for PC)

about mobile suport, WebGL is not "too fast" and mobile are too limited with resources...
even on PC WebGL1/2 allow to develop like 10year old "graphic" with high resource usage

Mobile browsers (firefox/safari/Android Browser) have WebGL support
where to check actual informatin I do not know
